name: Repository Dispatch

on:
  repository_dispatch:
    types: [released_merged]

jobs:
  my_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Run a script
        run: echo "This workflow was triggered by a repository_dispatch event with release version ${{ github.event.client_payload.version }}."

